# Generated by Django 4.2 on 2024-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_gallery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
