# Generated by Django 4.2 on 2024-10-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_practice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_name',
            field=models.ImageField(blank=True, max_length=2024, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('Sofa and Bed', 'Sofa and Bed'), ('Modular Kitchen', 'Modular Kitchen'), ('Table and Chairs', 'Table and Chairs'), ('Cupboard', 'Cupboard'), ('Wall Decore', 'Wall Decore'), ('TV Cabinet', 'TV Cabinet'), ('Door', 'Door'), ('Wooden Art', 'Wooden Art'), ('Other', 'Other')], default='Sofa and Bed', max_length=255),
        ),
    ]
